# Generated by Django 2.2.6 on 2019-10-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
    ]
