# Generated by Django 2.2.6 on 2019-10-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0002_auto_20191024_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
