# Generated by Django 2.2.6 on 2019-10-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0004_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='filtros',
            field=models.ManyToManyField(to='tp_acp1.Filtro'),
        ),
    ]
