# Generated by Django 2.2.6 on 2019-10-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0006_promocion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDelDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=30)),
                ('cafe', models.BooleanField()),
                ('opciones', models.CharField(max_length=400)),
                ('activo', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tp_acp1.Plato')),
                ('plato_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tp_acp1.Plato')),
                ('postre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tp_acp1.Plato')),
            ],
        ),
    ]
