# Generated by Django 2.2.6 on 2019-10-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0007_menudeldia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudeldia',
            name='fecha',
        ),
    ]
