# Generated by Django 2.2.6 on 2019-10-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0008_remove_menudeldia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('sugerencia', models.CharField(max_length=800)),
            ],
        ),
    ]
