# Generated by Django 2.2.6 on 2019-11-07 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0011_auto_20191027_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='menudeldia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='menudeldia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menudeldia',
            name='opciones',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='filtros',
            field=models.ManyToManyField(null=True, to='tp_acp1.Filtro'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/plato'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
