# Generated by Django 2.2.6 on 2019-11-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp_acp1', '0012_auto_20191107_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudeldia',
            name='opciones',
        ),
        migrations.AddField(
            model_name='menudeldia',
            name='bebida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tp_acp1.Plato'),
        ),
    ]
